import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        bg: "hsl(var(--bg))",
        err: "hsl(var(--err))",
        "err-con": "hsl(var(--err-con))",
        "iv-on-sf": "hsl(var(--iv-on-sf))",
        "iv-pr": "hsl(var(--iv-pr))",
        "iv-sf": "hsl(var(--iv-sf))",
        "on-bg": "hsl(var(--on-bg))",
        "on-err": "hsl(var(--on-err))",
        "on-err-con": "hsl(var(--on-err-con))",
        "on-pr": "hsl(var(--on-pr))",
        "on-pr-con": "hsl(var(--on-pr-con))",
        "on-pr-fx": "hsl(var(--on-pr-fx))",
        "on-pr-fx-var": "hsl(var(--on-pr-fx-var))",
        "on-sec": "hsl(var(--on-sec))",
        "on-sec-con": "hsl(var(--on-sec-con))",
        "on-sec-fx": "hsl(var(--on-sec-fx))",
        "on-sec-fx-var": "hsl(var(--on-sec-fx-var))",
        "on-sf": "hsl(var(--on-sf))",
        "on-sf-var": "hsl(var(--on-sf-var))",
        "on-ter": "hsl(var(--on-ter))",
        "on-ter-con": "hsl(var(--on-ter-con))",
        "on-ter-fx": "hsl(var(--on-ter-fx))",
        "on-ter-fx-var": "hsl(var(--on-ter-fx-var))",
        outline: "hsl(var(--outline))",
        "outline-var": "hsl(var(--outline-var))",
        pr: "hsl(var(--pr))",
        "pr-con": "hsl(var(--pr-con))",
        "pr-fx": "hsl(var(--pr-fx))",
        "pr-fx-dim": "hsl(var(--pr-fx-dim))",
        scrim: "hsl(var(--scrim))",
        sec: "hsl(var(--sec))",
        "sec-con": "hsl(var(--sec-con))",
        "sec-fx": "hsl(var(--sec-fx))",
        "sec-fx-dim": "hsl(var(--sec-fx-dim))",
        shadow: "hsl(var(--shadow))",
        sf: "hsl(var(--sf))",
        "sf-bright": "hsl(var(--sf-bright))",
        "sf-con": "hsl(var(--sf-con))",
        "sf-con-hg": "hsl(var(--sf-con-hg))",
        "sf-con-hgest": "hsl(var(--sf-con-hgest))",
        "sf-con-lw": "hsl(var(--sf-con-lw))",
        "sf-con-lwest": "hsl(var(--sf-con-lwest))",
        "sf-dim": "hsl(var(--sf-dim))",
        "sf-tint": "hsl(var(--sf-tint))",
        "sf-var": "hsl(var(--sf-var))",
        ter: "hsl(var(--ter))",
        "ter-con": "hsl(var(--ter-con))",
        "ter-fx": "hsl(var(--ter-fx))",
        "ter-fx-dim": "hsl(var(--ter-fx-dim))",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
} satisfies Config;
